AWSCONF_SHEET = 'contentfiles2aws'
PROJECTNAME = 'collective.contentfiles2aws'

ADD_PERMISSIONS = {
    'AWSFile': 'collective.contentfiles2aws: Add AWSFile',
    'AWSImage': 'collective.contentfiles2aws: Add AWSImage',
}

SKIP_SOURCE_REMOVE_FLAG = 'collective.contentfiles2aws.skip_aws_source_remove'
ABORT_TRANSACTION_FLAG = 'collective.contentfiles2aws.abort_transaction'

STORAGES_PNAME = "STORAGES"
AWS_STORAGE = "AWS"
FS_STORAGE = "FILESYSTEM"
STORAGE_OFF = "NONE"
STORAGES = (AWS_STORAGE, FS_STORAGE)
STORAGES_VALUES = (STORAGE_OFF,) + STORAGES
ACTIVE_STORAGE_PNAME = "ACTIVE_STORAGE"
FS_STORAGE_PNAME = "FILESYSTEM_STORAGE_PATH"
AWS_KEY_ID_PNAME = "AWS_KEY_ID"
AWS_SECRET_PNAME = "AWS_SECRET_KEY"
AWS_BUCKET_NAME_PNAME = "AWS_BUCKET_NAME"
AWS_FILENAME_PREFIX_PNAME = "AWS_FILENAME_PREFIX"
FS_STORAGE_PATH_PNAME = "FS_STORAGE_PATH"
ALTERNATIVE_CDN_DOMAIN_PNAME = "ALT_DOMAIN"
DEFAULT_METADATA_PNAME = "DEFAULT_METADATA"
AWS_CONF_PROP_NAMES = [ACTIVE_STORAGE_PNAME, FS_STORAGE_PNAME,
                       AWS_KEY_ID_PNAME, AWS_SECRET_PNAME,
                       AWS_BUCKET_NAME_PNAME, AWS_FILENAME_PREFIX_PNAME,
                       FS_STORAGE_PATH_PNAME, ALTERNATIVE_CDN_DOMAIN_PNAME,
                       DEFAULT_METADATA_PNAME]
